# Enrollment Analytics Pipeline Configuration
# 
# This configuration file defines all settings for the enrollment tracking pipeline.
# Customize these values for your institution's specific requirements.

# Institution Information
institution:
  name: "Your University"
  semester_term: "Fall 2024"
  academic_year: "2024-2025"
  
# Database Configuration
database:
  # Airflow connection ID for your student information system
  connection_id: "student_db_conn"
  
  # Database type (postgres, mssql, mysql, oracle)
  type: "postgres"
  
  # SQL query to extract enrollment data
  # This query should return at minimum: student_id, student_name
  # Additional fields like division, program, level are recommended
  sql_query: |
    SELECT DISTINCT 
        s.student_id,
        CONCAT(s.first_name, ' ', s.last_name) as student_name,
        s.email,
        s.division,
        s.program,
        s.level,
        s.status
    FROM students s
    JOIN enrollments e ON s.student_id = e.student_id
    WHERE e.semester = 'Fall'
      AND e.academic_year = EXTRACT(YEAR FROM CURRENT_DATE)
      AND e.status = 'Active'
      AND s.status NOT IN ('Withdrawn', 'Graduated')
    ORDER BY s.student_id

# Data Processing Configuration  
processing:
  # Column mapping for your data
  columns:
    student_id: "student_id"        # Primary identifier column
    student_name: "student_name"    # Student name column
    division: "division"            # Academic division/college
    program: "program"              # Program of study
    level: "level"                  # Academic level (Undergraduate, Graduate, etc.)
  
  # File storage locations (will be created if they don't exist)
  directories:
    output: "/opt/airflow/data/enrollment/snapshots"
    reports: "/opt/airflow/data/enrollment/reports"
    
  # Data retention settings
  retention:
    snapshot_files: 90  # Days to keep snapshot files
    report_files: 365   # Days to keep report files

# Analytics Configuration
analytics:
  # Anomaly detection sensitivity (standard deviations)
  anomaly_threshold: 2.0
  
  # Minimum data points required for trend analysis
  min_data_points: 5
  
  # Chart generation settings
  charts:
    enabled: true
    format: "png"
    dpi: 300
    
    # Color scheme for charts
    colors:
      primary: "#2E4057"      # Dark blue-gray
      accent: "#4caf50"       # Green
      warning: "#ff9800"      # Orange
      error: "#f44336"        # Red
      
    # Figure sizes (width, height in inches)
    figure_sizes:
      trend_chart: [14, 8]
      daily_changes: [14, 6]
      retention_analysis: [14, 6]
      dashboard: [16, 12]

# Notification Configuration
notifications:
  # Email settings
  email:
    enabled: true
    recipients:
      - "enrollment@university.edu"
      - "registrar@university.edu"
      - "data-team@university.edu"
    
    # Email template settings
    template:
      subject_prefix: "[Enrollment Alert]"
      include_charts: true
      include_student_lists: false  # Set to true to include add/drop lists
      
    # When to send notifications
    triggers:
      daily_summary: true
      anomaly_detected: true
      error_occurred: true

# Scheduling Configuration
scheduling:
  # Timezone for all operations
  timezone: "America/New_York"
  
  # When to run the pipeline (cron format)
  # Default: Daily at 8:00 AM
  schedule: "0 8 * * *"
  
  # Execution settings
  max_active_runs: 1
  catchup: false
  retries: 1
  retry_delay_minutes: 5

# Advanced Settings
advanced:
  # Performance tuning
  performance:
    batch_size: 10000          # Records to process in batches
    parallel_processing: false  # Enable for large datasets
    memory_optimization: true   # Optimize for memory usage
    
  # Data quality checks
  data_quality:
    enabled: true
    checks:
      - "duplicate_student_ids"
      - "missing_required_fields"  
      - "invalid_data_formats"
      - "enrollment_count_validation"
    
    # Thresholds for data quality alerts
    thresholds:
      max_duplicate_rate: 0.01      # 1% duplicates
      max_missing_data_rate: 0.05   # 5% missing data
      min_enrollment_change: -100   # Alert if >100 students drop
      max_enrollment_change: 200    # Alert if >200 students add

# Integration Settings
integrations:
  # Business Intelligence tools
  bi_tools:
    power_bi:
      enabled: false
      export_format: "csv"
      connection_string: ""
    
    tableau:
      enabled: false
      export_format: "csv"
      server_url: ""
      
  # Data warehouse integration
  data_warehouse:
    enabled: false
    connection_id: "warehouse_conn"
    target_schema: "enrollment_analytics"
    
  # External APIs (for enrichment)
  external_apis:
    student_system:
      enabled: false
      base_url: ""
      api_key_variable: "STUDENT_API_KEY"